- CONTRIBUTING.md
- code-of-conduct.md
Documents https://github.com/babylonhealth/certificate-transparency-android/issues/36
> Document how to build the project for contributing

- README.md
Documents https://github.com/babylonhealth/certificate-transparency-android/issues/51
> Add documentation about certificate revocation

- certificatetransparency/build.gradle.kts
- certificatetransparency/src/main/kotlin/com/babylon/certificatetransparency/internal/loglist/CallExt.kt
- certificatetransparency/src/main/kotlin/com/babylon/certificatetransparency/loglist/LogListDataSourceFactory.kt
- certificatetransparency/src/test/kotlin/com/babylon/certificatetransparency/loglist/LogListDataSourceFactoryTest.kt
Fixes https://github.com/babylonhealth/certificate-transparency-android/issues/59
> Increase default network timeout

- certificatetransparency/build.gradle.kts
> Add explicit dependency on bcutil

- sampleapp/lint.xml
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/item/ExampleCardItem.kt
> Suppress lint warnings in sample app

- README.md
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyBase.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/model/Host.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyBaseTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyHostnameVerifierIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyInterceptorIntegrationTest.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/ExampleScreen.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/BaseExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/State.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/httpurlconnection/HttpURLConnectionJavaExampleViewModel.java
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/httpurlconnection/HttpURLConnectionKotlinExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/okhttp/OkHttpJavaExampleViewModel.java
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/okhttp/OkHttpKotlinExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/volley/VolleyJavaExampleViewModel.java
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/volley/VolleyKotlinExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/item/OutlineButtonItem.kt
- sampleapp/src/main/res/drawable/minus.xml
- sampleapp/src/main/res/values/strings.xml
- sampleapp/src/main/resources/httpurlconnection-java.txt
- sampleapp/src/main/resources/httpurlconnection-kotlin.txt
- sampleapp/src/main/resources/okhttp-java.txt
- sampleapp/src/main/resources/okhttp-kotlin.txt
- sampleapp/src/main/resources/volley-java.txt
- sampleapp/src/main/resources/volley-kotlin.txt
Fixes #17 (originally https://github.com/babylonhealth/certificate-transparency-android/issues/70)
> Update includeHosts/excludeHosts rules to include all by default

- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/loglist/LogListDataSourceFactory.kt
> Allow creating OkHttpClient lazily

- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/LogListVerifier.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/RawLogListToLogListResultTransformer.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/loglist/LogListCacheManagementDataSource.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/loglist/LogListDataSourceFactory.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/LogListVerifierTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/RawLogListToLogListResultTransformerTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/loglist/LogListCacheManagementDataSourceTest.kt
Addresses one of the issues from #12
> Allow setting public key externally

- .github/workflows/autorelease.yml
- buildSrc/src/main/kotlin/UpdateLogListTask.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/loglist/LogListCacheManagementDataSource.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/loglist/LogListCacheManagementDataSourceTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/loglist/LogListDataSourceFactoryTest.kt
> Ensure the resources cache is actually used

- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/DefaultPolicy.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/verifier/DefaultPolicyTest.kt
> Verify there are just 2 distinct operators

- build.gradle.kts
- certificatetransparency/build.gradle.kts
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/utils/PublicKeyExt.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/utils/PublicKeyExtTest.kt
- sampleapp/build.gradle.kts
> Remove unused sha1Hash code

- certificatetransparency-android/build.gradle.kts
- certificatetransparency/build.gradle.kts
> Tweak kotlinc compiler options to disable StringConcatFactory

- certificatetransparency-android/build.gradle.kts
- certificatetransparency/build.gradle.kts
- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/internal/revoker/CertificateRevocationBase.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/datasource/DataSource.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/datasource/DataSourceReuseInflightTest.kt
- gradle/libs.versions.toml
> Ensure reuseInFlight jobs don't get stuck when cancelled

- README.md
Add a note to readme regarding issue #51
> Update note about WebViews and issues running on API 23 and lower

- .github/workflows/main.yml
- README.md
- certificatetransparency-android/consumer-proguard-rules.pro
- sampleapp/src/main/AndroidManifest.xml
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/ExampleScreen.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/MainActivity.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/MainScreen.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/WebViewScreen.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/trustmanager/WebViewExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/item/ExampleCardItem.kt
- sampleapp/src/main/res/values/strings.xml
- sampleapp/src/main/res/xml/data_extraction_rules.xml
> Update consumer-proguard.pro to fix web views

- .github/workflows/autorelease.yml
- .github/workflows/loglist.yml
- .github/workflows/main.yml
Updating workflows based on codeql feedback
> Set build permissions to least privilege

- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/CRHostnameVerifierBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/CRInterceptorBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/internal/revoker/CertificateRevocationHostnameVerifier.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/internal/revoker/CertificateRevocationInterceptor.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/CTHostnameVerifierBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/CTInterceptorBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/CTTrustManagerBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyHostnameVerifier.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyInterceptor.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyTrustManagerBasic.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyTrustManagerExtended.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificaterevocation/CertificateRevocationHostnameVerifierIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificaterevocation/CertificateRevocationInterceptorIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyHostnameVerifierIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyInterceptorIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyProviderIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyTrustManagerBasicIntegrationTest.kt
> Allow failOnError to be dynamically changed

- README.md
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/BaseLog.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/Log.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/Operator.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/TiledLog.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/LogListJsonParserV3.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/LogListJsonParserV3Test.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/utils/TestData.kt
- certificatetransparency/src/test/resources/testdata/loglist/log_list_tiled_logs.json
This also ensures an empty logs entry is accepted addressing #143
> Add support for tiled logs.

- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/CRHostnameVerifierBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/CRInterceptorBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/internal/revoker/CertificateRevocationHostnameVerifier.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificaterevocation/internal/revoker/CertificateRevocationInterceptor.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/CTHostnameVerifierBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/CTInterceptorBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/CTTrustManagerBuilder.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyHostnameVerifier.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyInterceptor.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyTrustManagerBasic.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyTrustManagerExtended.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyHostnameVerifierIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyInterceptorIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyProviderIntegrationTest.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/CertificateTransparencyTrustManagerBasicIntegrationTest.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/httpurlconnection/HttpURLConnectionKotlinExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/okhttp/OkHttpKotlinExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/trustmanager/TrustManagerKotlinExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/trustmanager/WebViewExampleViewModel.kt
- sampleapp/src/main/java/com/appmattus/certificatetransparency/sampleapp/examples/volley/VolleyKotlinExampleViewModel.kt
> failOnError result propagation

- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/FinalTreeHead.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/Log.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/Operator.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/model/v3/TiledLog.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/LogListJsonParserV3.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/utils/ThrowableExt.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/LogSignatureVerifier.kt
- certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/loglist/LogListResult.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/internal/loglist/parser/LogListJsonParserV3Test.kt
- certificatetransparency/src/test/kotlin/com/appmattus/certificatetransparency/utils/TestData.kt
- certificatetransparency/src/test/resources/testdata/loglist/log_list_no_operator_name.json
The recent downtime highlighted the parsing code doesn't handle exceptions throughly and don't fallback correctly as the code is supposed to.
This PR ensures all parsing exceptions are correctly caught and handled.
> Ensure generic exceptions in parsing are properly handled
